services:
  - type: web
    name: ai-gmail-phishing-detector
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    # Use Procfile for gunicorn config

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM_EMAIL
        value: onboarding@resend.dev
